image: registry.gitlab.com/christiantragesser/pypline-ci:poc

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    LOCAL_TAG: local/dagobah-motion
    EXT_TAG: $CI_REGISTRY/christiantragesser/dagobah-motion
    
services:
- name: docker:stable-dind

stages:
  - release

release:
  stage: release
  tags:
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $LOCAL_TAG -f $CI_PROJECT_DIR/docker/Dockerfile $CI_PROJECT_DIR/docker
    - docker tag $LOCAL_TAG ${EXT_TAG}:latest 
    - docker tag ${EXT_TAG}:latest ${EXT_TAG}:master-${CI_COMMIT_SHORT_SHA}
    - docker push ${EXT_TAG}:latest | grep -e "The push refers to" -e latest
    - docker push ${EXT_TAG}:master-${CI_COMMIT_SHORT_SHA} | grep -e "The push refers to" -e latest
  only:
    - master
